from enum import Enum

class TipoMovimiento(str, Enum):
    INGRESO = "INGRESO"
    EGRESO = "EGRESO"
    
class TipoCategoria(str, Enum):
    ALIMENTACION_HOGAR = "ALIMENTACION HOGAR"
    PIQUEOS_Y_COMIDA_FUERA = "PIQUEOS Y COMIDA FUERA"
    TRANSPORTE_Y_MOVILIDAD = "TRANSPORTE Y MOVILIDAD"
    SERVICIOS_Y_SUSCRIPCIONES = "SERVICIOS Y SUSCRIPCIONES"
    CUIDADO_PERSONAL = "CUIDADO PERSONAL"
    SALUD = "SALUD"
    ENTRETENIMIENTO_Y_SOCIAL = "ENTRETENIMIENTO Y SOCIAL"
    EDUCACION_Y_TRABAJO = "EDUCACION Y TRABAJO"
    VARIOS_E_IMPREVISTOS = "VARIOS E IMPREVISTOS"
    INGRESOS = "INGRESOS"